### PR TITLE
Parallelize

### PR DESCRIPTION
**Pull request by jd-source**
Hi Luc,

I found DSS very useful, and wanted to contribute back some improvements.
I noticed that despite being parallel, the CPU usage during registration was very spiky and not using 100% of my cores.
I added a generic TaskPool that I derived from MultiTask and used it to parallelize registration more uniformly. 

On my test, registration is now twice as fast.
There are some more tweaks we can use to make it slightly faster, but I'd first like to see this change accepted before pursuing. My next focus would be stacking.

As a note, I have a very rudimentary test, but I think the project from some official ones.
I suggest having a few scripts that automate downloading sample stacks and run them through DDS-CL and compare to previous versions. This would work very well for registration at least.

Thanks.

Jerome

### CODE REVIEW

**Comment by perdrix52** [comment]
I'm totally in favour of this, but don't have time thoroughly to review the code changes myself as I'm tied up acting as executor for my parents' estate.   I've asked Tony and Luc if they can review and approve these changes.

**Comment by perdrix52** [comment]
Please can you provide some information about yourself (and perhaps update your GitHub profile which currently shows nothing about you).  I'd like to invite you to join our "Slack" discussion group.

**Comment by jd-source** [comment]
Hi David,

My name is Jerome. I live in California and yet find many nights where the sky is not available :)
This gives some time to code when I'm bored and can't get to sleep.

**Comment by perdrix52** [comment]
Hi Jerome -Please can you let me have your email address as well and surname if you're OK with that.

**Comment by jd-source** [comment]
Hi David,

my email is jerome.d.github@gmail.com and I go by nop :)

**Comment by tonk777** [comment]
How can I test this if I build from this branch. What am I expecting to see?

**Comment by jd-source** [comment]
Hi Tony,

I think you can easily get the code by downloading a zip file of the repo from the github web site.
This is probably not the most elegant solution, since it by-passes git, but it would make it easy to test it.

I tested this by loading a set of images under dss GUI and saved a config file.

I then ran the dds command line on the config file to perform registration.

I timed how long it took to run with and without my changes.
I compared the registration files created with the two runs, and they were identical.

I know my change is probably not safe in GUI mode because of the progress reporter.
So initially, it could be enabled in command line mode only.

If you know of a good public source of astro stacks, that can be downloaded from a url, I'd happily automate the download and run of the 2 versions, and add that to the project so we could start a test-suite.

Jerome

**Comment by perdrix52** [comment]
If the change isn't safe to incorporate into DSS (as compared to DSSCL), them I'm not sure I'm happy about accepting it.   I am in favour of any performance increase, but not one that potentially breaks the GUI,

David

**Comment by perdrix52** [comment]
Hi Jerome,  Much as we like the idea we feel that we really can't accept the code until it also works withou breaking the GUI progress indicator. I'm closing this without merge.  If you do find the time to complete the exercise, well be happy to incorporate your changes.

David

**Comment by jd-source** [comment]
Hi David, 
I understand your concern.

I'd like to point out that as it stands, my change **does not break** the GUI progress indicator, since it is only enabled in DDSCL.
It would however require some work to make it work in a GUI context.

Are you open to considering inclusion in DDSCL and request a workable solution for GUI down the line?

Jerome

**Pull request closed without merging**
