### PR TITLE
Preliminary changes to better support bit depths/channel counts

### PR DESCRIPTION
**Pull request by gavin-olson**
I fixed up IsOtherPicture() to read out the PixelFormat of the image and handle the ones that easily map to existing DSS formats. I then switched up how LoadOtherPicture() works to instantiate the appropriate type of CColor/GrayBitmapT for the picture and to read it out by scanline instead of by pixel (saving having to work out the pixel widths, since the BitmapData struct gives us the scanline stride). I don't have a Windows development environment to test this in, but I think it's the gist of how it could work.

### CODE REVIEW

**Comment by perdrix52** [comment]
From the recent forum posts I see what this is attempting to achieve.  A *lot* more commentary would be good.  Given that you've not been able to compile it, let alone test it, I'm wary about accepting this into the development tip (master).    I'll ask if any of the other guys on the team want to run with this, and if so, will create a fork into which this could be merged

**Comment by gavin-olson** [comment]
I saw the exchange on the mailing list a while back about starting to use feature branches. I'm still sort of new to the GitHub thing; I'll need to look into how a PR can suggest a new branch instead of a merge into an existing one.

As for the patch itself, I'm working on getting a Windows development environment set up so I can compile things. I think it all definitely bears more discussion as to how deep changes should reach into the bitmap infrastructure. I touched as little as possible to get something out there, but looking at it it was a really klugy way to do it.

**Comment by perdrix52** [comment]
So are you saying that you’d prefer to spend more time to get it “right”?  If so I am happy to:

a)	close the current pull request 
b)	open a feature branch off master called DeepPng for you to work on

I'll try to get Luc's attention to add you as a contributor to the github project.

**Comment by gavin-olson** [comment]
I definitely want to get it done right. Closing this PR is probably the correct course; code to go in the actual project will look much different.

Is the groups.io forum the right place to discuss philosophy surrounding code changes, or is there a GitHub venue that's more appropriate?

**Comment by perdrix52** [comment]
Let me have your email and I'll invite you to join our Slack discussion group.

As requested I'm closing this ...

**Pull request closed without merging**
